development:
  adapter: postgresql
  encoding: unicode
  database: game-lister-development
  pool: 2
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: game-lister-production
